# This file instructs Redocly's linter to ignore the rules contained for specific parts of your API.
# See https://redoc.ly/docs/cli/ for more information.
openapi/management.yaml:
  tag-description:
    - '#/tags/0/description'
    - '#/tags/1/description'
    - '#/tags/2/description'
    - '#/tags/3/description'
    - '#/tags/5/description'
    - '#/tags/6/description'
    - '#/tags/7/description'
    - '#/tags/8/description'
    - '#/tags/9/description'
    - '#/tags/10/description'
    - '#/tags/11/description'
    - '#/tags/12/description'
    - '#/tags/13/description'
    - '#/tags/14/description'
    - '#/tags/15/description'
    - '#/tags/16/description'
    - '#/tags/17/description'
    - '#/tags/18/description'
    - '#/tags/19/description'
    - '#/tags/20/description'
    - '#/tags/21/description'
    - '#/tags/22/description'
    - '#/tags/23/description'
    - '#/tags/24/description'
    - '#/tags/25/description'
    - '#/tags/26/description'
    - '#/tags/27/description'
    - '#/tags/28/description'
    - '#/tags/29/description'
  no-ambiguous-paths:
    - '#/paths/~1api~1v1~1groups~1{groupId}~1apps'
    - '#/paths/~1api~1v1~1groups~1{groupId}~1roles'
    - '#/paths/~1api~1v1~1groups~1{groupId}~1users'
  operation-summary:
    - '#/paths/~1api~1v1~1apps~1{appId}~1credentials~1keys~1generate/post/summary'
    - '#/paths/~1api~1v1~1apps~1{appId}~1grants/get/summary'
    - '#/paths/~1api~1v1~1apps~1{appId}~1grants/post/summary'
    - '#/paths/~1api~1v1~1apps~1{appId}~1grants~1{grantId}/get/summary'
    - '#/paths/~1api~1v1~1apps~1{appId}~1grants~1{grantId}/delete/summary'
    - '#/paths/~1api~1v1~1apps~1{appId}~1tokens/get/summary'
    - '#/paths/~1api~1v1~1apps~1{appId}~1tokens/delete/summary'
    - '#/paths/~1api~1v1~1apps~1{appId}~1tokens~1{tokenId}/get/summary'
    - '#/paths/~1api~1v1~1apps~1{appId}~1tokens~1{tokenId}/delete/summary'
    - '#/paths/~1api~1v1~1authorizationServers/get/summary'
    - '#/paths/~1api~1v1~1authorizationServers/post/summary'
    - '#/paths/~1api~1v1~1authorizationServers~1{authServerId}/get/summary'
    - '#/paths/~1api~1v1~1authorizationServers~1{authServerId}/put/summary'
    - '#/paths/~1api~1v1~1authorizationServers~1{authServerId}/delete/summary'
    - >-
      #/paths/~1api~1v1~1authorizationServers~1{authServerId}~1claims/get/summary
    - >-
      #/paths/~1api~1v1~1authorizationServers~1{authServerId}~1claims/post/summary
    - >-
      #/paths/~1api~1v1~1authorizationServers~1{authServerId}~1claims~1{claimId}/get/summary
    - >-
      #/paths/~1api~1v1~1authorizationServers~1{authServerId}~1claims~1{claimId}/put/summary
    - >-
      #/paths/~1api~1v1~1authorizationServers~1{authServerId}~1claims~1{claimId}/delete/summary
    - >-
      #/paths/~1api~1v1~1authorizationServers~1{authServerId}~1clients/get/summary
    - >-
      #/paths/~1api~1v1~1authorizationServers~1{authServerId}~1clients~1{clientId}~1tokens/get/summary
    - >-
      #/paths/~1api~1v1~1authorizationServers~1{authServerId}~1clients~1{clientId}~1tokens/delete/summary
    - >-
      #/paths/~1api~1v1~1authorizationServers~1{authServerId}~1clients~1{clientId}~1tokens~1{tokenId}/get/summary
    - >-
      #/paths/~1api~1v1~1authorizationServers~1{authServerId}~1clients~1{clientId}~1tokens~1{tokenId}/delete/summary
    - >-
      #/paths/~1api~1v1~1authorizationServers~1{authServerId}~1credentials~1keys/get/summary
    - >-
      #/paths/~1api~1v1~1authorizationServers~1{authServerId}~1credentials~1lifecycle~1keyRotate/post/summary
    - >-
      #/paths/~1api~1v1~1authorizationServers~1{authServerId}~1lifecycle~1activate/post/summary
    - >-
      #/paths/~1api~1v1~1authorizationServers~1{authServerId}~1lifecycle~1deactivate/post/summary
    - >-
      #/paths/~1api~1v1~1authorizationServers~1{authServerId}~1policies/get/summary
    - >-
      #/paths/~1api~1v1~1authorizationServers~1{authServerId}~1policies/post/summary
    - >-
      #/paths/~1api~1v1~1authorizationServers~1{authServerId}~1policies~1{policyId}/get/summary
    - >-
      #/paths/~1api~1v1~1authorizationServers~1{authServerId}~1policies~1{policyId}/put/summary
    - >-
      #/paths/~1api~1v1~1authorizationServers~1{authServerId}~1policies~1{policyId}/delete/summary
    - >-
      #/paths/~1api~1v1~1authorizationServers~1{authServerId}~1policies~1{policyId}~1lifecycle~1activate/post/summary
    - >-
      #/paths/~1api~1v1~1authorizationServers~1{authServerId}~1policies~1{policyId}~1lifecycle~1deactivate/post/summary
    - >-
      #/paths/~1api~1v1~1authorizationServers~1{authServerId}~1policies~1{policyId}~1rules/get/summary
    - >-
      #/paths/~1api~1v1~1authorizationServers~1{authServerId}~1policies~1{policyId}~1rules/post/summary
    - >-
      #/paths/~1api~1v1~1authorizationServers~1{authServerId}~1policies~1{policyId}~1rules~1{ruleId}/get/summary
    - >-
      #/paths/~1api~1v1~1authorizationServers~1{authServerId}~1policies~1{policyId}~1rules~1{ruleId}/put/summary
    - >-
      #/paths/~1api~1v1~1authorizationServers~1{authServerId}~1policies~1{policyId}~1rules~1{ruleId}/delete/summary
    - >-
      #/paths/~1api~1v1~1authorizationServers~1{authServerId}~1policies~1{policyId}~1rules~1{ruleId}~1lifecycle~1activate/post/summary
    - >-
      #/paths/~1api~1v1~1authorizationServers~1{authServerId}~1policies~1{policyId}~1rules~1{ruleId}~1lifecycle~1deactivate/post/summary
    - >-
      #/paths/~1api~1v1~1authorizationServers~1{authServerId}~1scopes/get/summary
    - >-
      #/paths/~1api~1v1~1authorizationServers~1{authServerId}~1scopes/post/summary
    - >-
      #/paths/~1api~1v1~1authorizationServers~1{authServerId}~1scopes~1{scopeId}/get/summary
    - >-
      #/paths/~1api~1v1~1authorizationServers~1{authServerId}~1scopes~1{scopeId}/put/summary
    - >-
      #/paths/~1api~1v1~1authorizationServers~1{authServerId}~1scopes~1{scopeId}/delete/summary
    - '#/paths/~1api~1v1~1eventHooks/get/summary'
    - '#/paths/~1api~1v1~1eventHooks/post/summary'
    - '#/paths/~1api~1v1~1eventHooks~1{eventHookId}/get/summary'
    - '#/paths/~1api~1v1~1eventHooks~1{eventHookId}/put/summary'
    - '#/paths/~1api~1v1~1eventHooks~1{eventHookId}/delete/summary'
    - >-
      #/paths/~1api~1v1~1eventHooks~1{eventHookId}~1lifecycle~1activate/post/summary
    - >-
      #/paths/~1api~1v1~1eventHooks~1{eventHookId}~1lifecycle~1deactivate/post/summary
    - >-
      #/paths/~1api~1v1~1eventHooks~1{eventHookId}~1lifecycle~1verify/post/summary
    - '#/paths/~1api~1v1~1features/get/summary'
    - '#/paths/~1api~1v1~1features~1{featureId}/get/summary'
    - '#/paths/~1api~1v1~1features~1{featureId}~1dependencies/get/summary'
    - '#/paths/~1api~1v1~1features~1{featureId}~1dependents/get/summary'
    - '#/paths/~1api~1v1~1features~1{featureId}~1{lifecycle}/post/summary'
    - '#/paths/~1api~1v1~1groups~1rules~1{ruleId}/put/summary'
    - '#/paths/~1api~1v1~1groups~1{groupId}~1roles/get/summary'
    - '#/paths/~1api~1v1~1groups~1{groupId}~1roles/post/summary'
    - '#/paths/~1api~1v1~1groups~1{groupId}~1roles~1{roleId}/get/summary'
    - '#/paths/~1api~1v1~1groups~1{groupId}~1roles~1{roleId}/delete/summary'
    - >-
      #/paths/~1api~1v1~1groups~1{groupId}~1roles~1{roleId}~1targets~1catalog~1apps/get/summary
    - >-
      #/paths/~1api~1v1~1groups~1{groupId}~1roles~1{roleId}~1targets~1catalog~1apps~1{appName}/put/summary
    - >-
      #/paths/~1api~1v1~1groups~1{groupId}~1roles~1{roleId}~1targets~1catalog~1apps~1{appName}/delete/summary
    - '#/paths/~1api~1v1~1idps~1{idpId}~1credentials~1csrs~1{csrId}/get/summary'
    - >-
      #/paths/~1api~1v1~1idps~1{idpId}~1credentials~1csrs~1{csrId}/delete/summary
    - >-
      #/paths/~1api~1v1~1idps~1{idpId}~1credentials~1csrs~1{csrId}~1lifecycle~1publish/post/summary
    - '#/paths/~1api~1v1~1idps~1{idpId}~1users~1{userId}/get/summary'
    - '#/paths/~1api~1v1~1inlineHooks/get/summary'
    - '#/paths/~1api~1v1~1inlineHooks/post/summary'
    - '#/paths/~1api~1v1~1inlineHooks~1{inlineHookId}/get/summary'
    - '#/paths/~1api~1v1~1inlineHooks~1{inlineHookId}/put/summary'
    - '#/paths/~1api~1v1~1inlineHooks~1{inlineHookId}/delete/summary'
    - '#/paths/~1api~1v1~1inlineHooks~1{inlineHookId}~1execute/post/summary'
    - >-
      #/paths/~1api~1v1~1inlineHooks~1{inlineHookId}~1lifecycle~1activate/post/summary
    - >-
      #/paths/~1api~1v1~1inlineHooks~1{inlineHookId}~1lifecycle~1deactivate/post/summary
    - '#/paths/~1api~1v1~1mappings/get/summary'
    - '#/paths/~1api~1v1~1meta~1schemas~1user~1{schemaId}/post/summary'
    - '#/paths/~1api~1v1~1meta~1schemas~1user~1linkedObjects/get/summary'
    - '#/paths/~1api~1v1~1meta~1schemas~1user~1linkedObjects/post/summary'
    - >-
      #/paths/~1api~1v1~1meta~1schemas~1user~1linkedObjects~1{linkedObjectName}/get/summary
    - >-
      #/paths/~1api~1v1~1meta~1schemas~1user~1linkedObjects~1{linkedObjectName}/delete/summary
    - '#/paths/~1api~1v1~1meta~1types~1user/get/summary'
    - '#/paths/~1api~1v1~1meta~1types~1user/post/summary'
    - '#/paths/~1api~1v1~1meta~1types~1user~1{typeId}/get/summary'
    - '#/paths/~1api~1v1~1meta~1types~1user~1{typeId}/put/summary'
    - '#/paths/~1api~1v1~1meta~1types~1user~1{typeId}/post/summary'
    - '#/paths/~1api~1v1~1meta~1types~1user~1{typeId}/delete/summary'
    - '#/paths/~1api~1v1~1policies/get/summary'
    - '#/paths/~1api~1v1~1policies/post/summary'
    - '#/paths/~1api~1v1~1policies~1{policyId}/get/summary'
    - '#/paths/~1api~1v1~1policies~1{policyId}/put/summary'
    - '#/paths/~1api~1v1~1policies~1{policyId}/delete/summary'
    - '#/paths/~1api~1v1~1policies~1{policyId}~1lifecycle~1activate/post/summary'
    - >-
      #/paths/~1api~1v1~1policies~1{policyId}~1lifecycle~1deactivate/post/summary
    - '#/paths/~1api~1v1~1policies~1{policyId}~1rules/get/summary'
    - '#/paths/~1api~1v1~1policies~1{policyId}~1rules/post/summary'
    - '#/paths/~1api~1v1~1policies~1{policyId}~1rules~1{ruleId}/get/summary'
    - '#/paths/~1api~1v1~1policies~1{policyId}~1rules~1{ruleId}/put/summary'
    - '#/paths/~1api~1v1~1policies~1{policyId}~1rules~1{ruleId}/delete/summary'
    - >-
      #/paths/~1api~1v1~1policies~1{policyId}~1rules~1{ruleId}~1lifecycle~1activate/post/summary
    - >-
      #/paths/~1api~1v1~1policies~1{policyId}~1rules~1{ruleId}~1lifecycle~1deactivate/post/summary
    - '#/paths/~1api~1v1~1threats~1configuration/get/summary'
    - '#/paths/~1api~1v1~1threats~1configuration/post/summary'
    - '#/paths/~1api~1v1~1trustedOrigins/get/summary'
    - '#/paths/~1api~1v1~1trustedOrigins/post/summary'
    - '#/paths/~1api~1v1~1trustedOrigins~1{trustedOriginId}/get/summary'
    - '#/paths/~1api~1v1~1trustedOrigins~1{trustedOriginId}/put/summary'
    - '#/paths/~1api~1v1~1trustedOrigins~1{trustedOriginId}/delete/summary'
    - >-
      #/paths/~1api~1v1~1trustedOrigins~1{trustedOriginId}~1lifecycle~1activate/post/summary
    - >-
      #/paths/~1api~1v1~1trustedOrigins~1{trustedOriginId}~1lifecycle~1deactivate/post/summary
    - '#/paths/~1api~1v1~1users~1{userId}/post/summary'
    - '#/paths/~1api~1v1~1users~1{userId}~1clients/get/summary'
    - >-
      #/paths/~1api~1v1~1users~1{userId}~1clients~1{clientId}~1grants/get/summary
    - >-
      #/paths/~1api~1v1~1users~1{userId}~1clients~1{clientId}~1grants/delete/summary
    - >-
      #/paths/~1api~1v1~1users~1{userId}~1clients~1{clientId}~1tokens/get/summary
    - >-
      #/paths/~1api~1v1~1users~1{userId}~1clients~1{clientId}~1tokens/delete/summary
    - >-
      #/paths/~1api~1v1~1users~1{userId}~1clients~1{clientId}~1tokens~1{tokenId}/get/summary
    - >-
      #/paths/~1api~1v1~1users~1{userId}~1clients~1{clientId}~1tokens~1{tokenId}/delete/summary
    - '#/paths/~1api~1v1~1users~1{userId}~1factors/get/summary'
    - '#/paths/~1api~1v1~1users~1{userId}~1factors~1catalog/get/summary'
    - '#/paths/~1api~1v1~1users~1{userId}~1factors~1questions/get/summary'
    - '#/paths/~1api~1v1~1users~1{userId}~1factors~1{factorId}/get/summary'
    - '#/paths/~1api~1v1~1users~1{userId}~1factors~1{factorId}/delete/summary'
    - >-
      #/paths/~1api~1v1~1users~1{userId}~1factors~1{factorId}~1transactions~1{transactionId}/get/summary
    - '#/paths/~1api~1v1~1users~1{userId}~1grants/get/summary'
    - '#/paths/~1api~1v1~1users~1{userId}~1grants/delete/summary'
    - '#/paths/~1api~1v1~1users~1{userId}~1grants~1{grantId}/get/summary'
    - '#/paths/~1api~1v1~1users~1{userId}~1grants~1{grantId}/delete/summary'
    - >-
      #/paths/~1api~1v1~1users~1{userId}~1linkedObjects~1{relationshipName}/get/summary
    - >-
      #/paths/~1api~1v1~1users~1{userId}~1linkedObjects~1{relationshipName}/delete/summary
    - '#/paths/~1api~1v1~1users~1{userId}~1roles/get/summary'
    - '#/paths/~1api~1v1~1users~1{userId}~1roles/post/summary'
    - '#/paths/~1api~1v1~1users~1{userId}~1roles~1{roleId}/get/summary'
    - '#/paths/~1api~1v1~1users~1{userId}~1roles~1{roleId}/delete/summary'
    - >-
      #/paths/~1api~1v1~1users~1{userId}~1roles~1{roleId}~1targets~1catalog~1apps/get/summary
    - >-
      #/paths/~1api~1v1~1users~1{userId}~1roles~1{roleId}~1targets~1catalog~1apps/put/summary
    - >-
      #/paths/~1api~1v1~1users~1{userId}~1roles~1{roleId}~1targets~1catalog~1apps~1{appName}/put/summary
    - >-
      #/paths/~1api~1v1~1users~1{userId}~1roles~1{roleId}~1targets~1catalog~1apps~1{appName}/delete/summary
    - >-
      #/paths/~1api~1v1~1users~1{userId}~1roles~1{roleId}~1targets~1groups/get/summary
    - >-
      #/paths/~1api~1v1~1users~1{userId}~1roles~1{roleId}~1targets~1groups~1{groupId}/put/summary
    - >-
      #/paths/~1api~1v1~1users~1{userId}~1roles~1{roleId}~1targets~1groups~1{groupId}/delete/summary
    - '#/paths/~1api~1v1~1users~1{userId}~1sessions/delete/summary'
  spec:
    - '#/paths/~1api~1v1~1captchas/get/x-codeSamples/0/source'
  no-unresolved-refs:
    - '#/paths/~1api~1v1~1captchas/get/x-codeSamples/0/source'
